version: '3.8'

services:
  spark:
    image: bitnami/spark:latest
    volumes:
      - ./src:/app
      - ./data:/app/data
      - ./requirements.txt:/app/requirements.txt
    working_dir: /app
    #command: ["spark-submit", "analysis.py"]
    environment:
      - SPARK_MODE=master